= Защита системной учётной записи

Системная учётная запись -- учётная запись пользователя, от имени которого сервис ({wc}, СУБП и пр.) должен подключаться к серверу {dv} при выполнении служебных операций. Пароль системной учётной записи {dv} может быть опционально защищён шифрованием. Имя учётной записи шифровать не требуется. В данном разделе приведено руководство по шифрованию.

Для шифрования паролей используется утилита _EncryptionTool_, которая может быть установлена на Linux или Windows.

NOTE: Для шифрования паролей потребуется использовать сертификаты RSA.

[#lin]
== Установка и запуск утилиты на Linux

В Linux утилита устанавливается следующей командой:

[source,bash]
----
sudo apt-get install docsvision-encryption
----

После установки утилита располагается по пути: `/usr/lib/docsvision/tools/encryption`.

Запустить утилиту можно из командной строки следующим образом:

.Запуск из директории установки:
[source,bash]
----
./encryption [command] [options]
----

.Запуск из любой директории:
[source,bash]
----
/usr/lib/docsvision/tools/encryption/encryption [command] [options]
----

[#win]
== Установка и запуск утилиты на Windows

В ОС Windows утилита будет установлена вместе с серверной частью модуля _{pl}_ и после установки располагается по пути `C:\Program Files (x86)\Docsvision\Platform\Tools`.

.Запуск из директории установки:
[source,shell]
----
encryption.exe [command] [options]
----

.Запуск из любой директории:
[source,shell]
----
"C:\Program Files (x86)\Docsvision\Platform\Tools\encryption.exe" [command] [options]
----

[#cr-cert]
== Создание сертификата шифрования в Linux

. Создайте пару ключей шифрования, выполнив следующие команды:
+
[source,bash]
----
cd ~
openssl req -newkey rsa:2048 -nodes -keyout docsvision.key -x509 -days 3654 -out docsvision.crt
----
+
В процессе выполнения команды появятся дополнительные вопросы для заполнения сертификата.
+
. Сгенерируйте и сохраните сертификат `docsvision.pfx`:
+
[source,bash]
----
openssl pkcs12 -inkey docsvision.key -in docsvision.crt -export -out docsvision.pfx
----
+
Пароль на сертификат указывать не нужно. Имена файлов ключей и пути можно указывать произвольные.
+
[[earlier]]Полученный сертификат в формате `.pfx` необходимо скопировать в каталог `~/.dotnet/corefx/cryptography/x509stores/my`. Если каталог отсутствует, создайте его самостоятельно.

Аналогичным образом сертификат можно сгенерировать в Windows и экспортировать в формате `.pfx` без пароля.

В Windows полученный сертификат необходимо установить в хранилище сертификатов текущего пользователя.

[#encode]
== Шифрование пароля учётной записи

.Чтобы зашифровать пароль, выполните следующие команды:
. Зашифруйте пароль при помощи сертификата, полученного на <<cr-cert,предыдущем шаге>>.
+
[source,bash]
----
./encryption encrypt [отпечаток сертификата]
----
+
Отпечаток сертификата можно получить, выполнив запрос
+
[source,bash]
----
openssl pkcs12 -in docsvision.pfx -nodes | openssl x509 -noout -fingerprint
----
+
. В окне терминала введите пароль системной учётной записи {dv}.
+
В ответ будет выведен зашифрованный пароль.
+
. Сохраните данные системной учётной записи {dv} (имя учётной записи и пароль в зашифрованном виде) предпочтительным способом:
+
.В виде переменных окружения:
****
* `DV_SystemUserAccount` -- имя системной учётной записи.
* `DV_SystemUserPassword` -- пароль системной учётной записи.
* `DV_DataProtectCertificateThumbprint` -- отпечаток сертификата шифрования.
****
+
.В конфигурационном файле программы:
****
Добавьте в конфигурационный файл программы `appsettings.json` три параметра на корневом уровне:

* `SystemUserAccount` -- имя системной учётной записи.
* `SystemUserPassword` -- пароль системной учётной записи.
* `DataProtectCertificateThumbprint` -- отпечаток сертификата шифрования.
****
+
. <<earlier,Если этого не было сделано ранее>>, установите сертификат шифрования в хранилище сертификатов текущего пользователя в ОС Windows и в каталог `~/.dotnet/corefx/cryptography/x509stores/my` в ОС Linux.
+
NOTE: Сертификат нужно добавлять в домашнюю папку пользователя, от имени которого запускается сервис. Например, для пользователя `root` (от имени пользователя ROOT службы запускаются по умолчанию) полный путь будет: `/root/.dotnet/corefx/cryptography/x509stores/my`. +
Если папка отсутствует, создайте её самостоятельно.
