= Защита системной учётной записи

Пароль системной учётной записи {dv} может быть опционально защищён шифрованием. Имя учётной записи шифровать не требуется. В данном разделе приведено руководство по шифрованию.

Для шифрования используется утилита _EncryptionTool_, которая может быть установлена следующей командой:

[source,bash]
----
 sudo apt-get install docsvision-encryption
----

После установки утилита располагается по пути: `/usr/lib/docsvision/tools/encryption`.

. Создайте пару ключей шифрования, выполнив следующие команды:
+
[source,bash]
----
cd ~
openssl genrsa -out platform.key 1024 <.>
openssl rsa -pubout -in platform.key -out platform.pub <.>
----
<.> Сгенерировать приватный ключ.
<.> Сгенерировать публичный ключ.
+
Публичный ключ необходимо скопировать на ПК с утилитой шифрования _EncryptionTool_.
+
Приватный ключ необходимо скопировать на ПК с сервером {dv}.
+
. Зашифруйте пароль системной учётной записи с помощью программы EncryptionTool:
+
[source,bash]
----
/usr/lib/docsvision/tools/encryption/encryption encrypt папка-с-ключом/platform.pub
----
+
.. Введите пароль системной учётной записи {dv}.
.. В консоль будет выведен пароль в зашифрованном виде.
+
. Сохраните зашифрованный пароль в конфигурации сервиса или программы, для работы которой требуется системная учетная запись. Подробнее см. раздел "xref:config-platform.adoc[]".
.. Сохраните данные системной учётной записи {dv} (имя учётной записи и пароль в зашифрованном виде) предпочтительным способом:
+
.В виде переменных окружения:
****
* `DV_SystemUserAccount` -- имя системной учётной записи
* `DV_SystemUserPassword` -- пароль системной учётной записи.
****
+
.В конфигурационном файле программы:
****
Добавьте в конфигурационный файл программы `appsettings.json` два параметра на корневом уровне:

* `SystemUserAccount` -- имя системной учётной записи
* `SystemUserPassword` -- пароль системной учётной записи.
****
+
. Для работы с шифрованными паролями системной учётной записи, необходимо указать путь к файлу закрытого ключа шифрования.
+
.. Скопируйте файл закрытого ключа на сервер {dv}. Файл должен быть доступен на чтение процессу сервера {dv}.
.. Откройте конфигурационный файл `appsettings.json` на сервере {dv}.
.. Добавьте параметр `DataProtectPrivateKeyPath` в корневой узел. В значение параметра необходимо указать расположение закрытого ключа шифрования.
// +
// NOTE: Расположение закрытого ключа можно также передать через переменную окружения -- `DV_DataProtectPrivateKeyPath`