:page-layout: home

= Активация лицензии

Для активации лицензии в системе {dv} реализована специальная утилита.

.Активировать систему можно следующими способами:
* При помощи данной утилиты активации, поставляемой с пакетом установки модуля {pl} при xref:install-platform.adoc[установке на ОС Linux].
** Утилиту можно установить отдельно командой:
+
[tabs]
====
Astra Linux::
+
 $ sudo apt-get install docsvision-activation

РЕД ОС::
+
 $ sudo dnf install docsvision-activation
====
+
** После установки утилиту можно запустить из директории `/usr/lib/docsvision/tools/activation`
// * При помощи "xref:.activation:util.adoc[]", входящей в комплект утилит _{rk}_.
// * Из программы "xref:platform:console:manage-licenses.adoc[{cns}]".

.Утилита активации предоставляет следующие возможности:
. Онлайн активация с параметром в виде ключа и адреса сервера.
. Офлайн активация:
.. Создание запроса на офлайн активацию.
.. Применение ответа на офлайн активацию.
.. Получение справки по активации при помощи команды help.

[#commands]
== Активация при помощи утилиты активации для Linux

. Запустите утилиту из любой директории командой:
+
 sudo /usr/lib/docsvision/tools/activation/activation
+
В окне запущенной командной строки будет выведена справка по использованию утилиты.
+
. Выполните активацию:
.. Для онлайн-активации введите серийный номер лицензионного ключа, выданный при покупке продукта, в параметр команды для онлайн активации:
+
 sudo /usr/lib/docsvision/tools/activation/activation online <серийный-номер-продукта>
+
.. Для офлайн-активации создайте файл запроса офлайн активации:
+
 offline <серийный-номер-продукта> <папка-для-сохранения-запроса>
+
Файл будет сохранён в формате `.xml` с указанием даты создания: `request-activation_ГГММДД_ЧЧММСС.xml`. Отправьте полученный файл запроса в компанию "ДоксВижн" на адрес электронной почты _sales@{dv}.com_.
.. Выберите файл, полученный от компании "ДоксВижн" на запрос активации и выполните офлайн активацию:
+
 activate <путь-к-файлу-активации>
+
. Дополнительные параметры утилиты активации:
+
--
* `--version` -- показать информацию о версии.
* `-?, -h, --help` -- показать справку и информацию об использовании.
--
+
NOTE: Если ввести команду без нужных аргументов, в окне терминала будет выведена справка для использованной команды.
