= Полезные команды

Ниже перечислены команды, которые могут быть полезны при установке и после неё. Команды приведены на примере модуля {pl}. Чтобы применить команду для другого модуля, замените `platform` на название модуля.

. Посмотреть состояние сервиса:
+
[source,bash]
----
sudo systemctl status dvappserver
----
+
. Запустить сервис:
+
[source,bash]
----
sudo systemctl start dvappserver
----
+
. Остановить сервис:
+
[source,bash]
----
sudo systemctl stop dvappserver
----
+
. Перезапустить сервис:
+
[source,bash]
----
sudo systemctl restart dvappserver
----
+
// tag::log[]
. Посмотреть журнал службы (только записи в `stdout/stderr`):
+
[source,bash,subs=attributes+]
----
sudo journalctl -u {serv} <.>
----
<.> `dvappserver` -- имя перезапускаемой службы.
+
. Посмотреть только самые последние записи в журнале и выводить новые записи по мере их появления:
+
[source,bash]
----
sudo journalctl -f -u dvappserver <.>
----
<.> Замените `dvappserver` на имя нужного сервиса.
// end::log[]
+
. Установить пакет:
+
[source,bash]
----
sudo apt-get install docsvision-platform
----
+
. Установить пакет определенной версии:
+
[source,bash]
----
sudo apt-get install docsvision-platform=6.0.1
----
+
. Удалить пакет:
+
[source,bash]
----
sudo apt-get purge docsvision-platform
----
+
. Удалить ненужные системе пакеты (зависимости, которые принесли за собой другие пакеты при установке) командой:
+
[source,bash]
----
sudo apt-get autoremove
----