= Установка серверных компонентов на Windows

include::partial$limitation.adoc[]

include::installguide::partial$doNotStart.adoc[]

Пользователь, выполняющий установку, должен обладать правами администратора.

// tag::other-windows[]
.Для установки компонентов потребуется:
* ASP.NET Core Runtime (Hosting Bundle)
* .NET Desktop Runtime (x86/x64)

. Запустите последовательно пакеты установки серверной части базовых модулей:
+
. {pl}.
. {ad}.
. {bo}.
. {dm}.
. {to}.
. {wincl}.
. {wf}.
. Служба {ws}.
+
При установке Службы {ws} на шаге выбора компонентов оставьте только _Серверные компоненты_, компонент _Служба {ws}_ не требуется.
+
. {mc}.
. {wc}.
+
При установке {wc}а на шаге `Укажите базы данных из числа подключенных к серверу, в которые следует установить Web-клиент` выберите *Отмена*.
+
. В реестре машины укажите фактический адрес Linux-сервера, на котором установлен сервер {dv}:
+
 reg add HKEY_LOCAL_MACHINE\SOFTWARE\DocsVision\Platform\Site /v ServerURL /t REG_SZ /d http://dvserver.domain.com:5000/api/v1
+
. Добавьте данные системной учётной записи {dv} в переменные окружения.
+
Под этой учётной записью Консоль настройки будет подключаться к серверу {dv}.
+
 setx DV_SystemUserAccount account@domain.com
 setx DV_SystemUserPassword password

// end::other-windows[]
