= Установка серверных компонентов на Windows

include::partial$limitation.adoc[]

include::installguide::partial$doNotStart.adoc[]

// tag::other-windows[]
.Для установки компонентов потребуется:
* {asp-bundle} и выше.
* {net-r} и выше.

Пользователь, выполняющий установку, должен обладать правами администратора.

. Запустите последовательно пакеты установки серверной части базовых модулей:
+
* {pl}.
* Служба {ws}.
+
При установке Службы {ws} на шаге выбора компонентов оставьте только _Серверные компоненты_, компонент _Служба {ws}_ не требуется.
+
* {ad}.
* {bo}.
* {dm}.
* {to}.
* {wc}.
+
При появлении окна "Мастера настройки {dv}", закройте мастер нажатием кнопки *Отмена*. +
// После установки {wc}а на Windows возможны ошибки вида: `Unexpected error occurred. System.Management currently is only supported for Windows desktop applications`. Подобные ошибки являются нормальным явлением.
+
После установки и настройки  {wc}а, выполните настройку программ панели управления {wc}ом и Конструктора Web-разметок. См. раздел "xref:webclient:admin:install-server-windows.adoc#kvr-pu[Установка программ Конструктор Web-разметок и Панель управления]" в документации по администрированию {wc}а.
+
* {wincl}.
* {wf}.
. В реестре машины укажите фактический адрес Linux-сервера, на котором установлен сервер {dv}:
+
 reg add HKEY_LOCAL_MACHINE\SOFTWARE\DocsVision\Platform\Site /v ServerURL /t REG_SZ /d http://dvserver.domain.com:5000/api/v1
+
. Добавьте данные системной учётной записи {dv} в переменные окружения.
+
Под этой учётной записью Консоль настройки будет подключаться к серверу {dv}.
+
 setx DV_SystemUserAccount account@domain.com
 setx DV_SystemUserPassword password

// end::other-windows[]
