= Установка базовых модулей на Linux

Данный раздел описывает установку базовых модулей для ОС Linux. Все описанные ниже команды необходимо выполнять после завершения xref:install-platform.adoc[установки] модуля {pl}.

При установке модулей {dv} в ОС Linux разделение на серверную и клиентскую части отсутствует. Установка выполняется описанными ниже командами, другие базовые модули будут установлены автоматически.

[#webc]
== Установка {wc}а

. Установите службу модуля:
+
[source,bash]
----
sudo apt-get install webclient
----
+
. Замените или отредактируйте файл настроек модуля:
+
[source,bash]
----
sudo cp ~/tech_days/WebClient/appsettings.json /usr/lib/docsvision/WebClient/appsettings.json
----
+
. Запустите службу {wc}а:
+
[source,bash]
----
sudo systemctl start webclient
----
+
. Теперь вы можете запустить {wc}, перейдя по адресу: `\http://WebC-server.domain.com/Account/Login`.

[#sett-serv]
== Установка Сервиса настроек

. Установите сервис:
+
[source,bash]
----
sudo apt-get install settingsservice
----
+
. Замените или отредактируйте файл настроек:
+
[source,bash]
----
sudo cp ~/tech_days/SettingsService/appsettings.json /usr/lib/docsvision/SettingsService/appsettings.json
----
+
. Запустите сервис:
+
[source,bash]
----
sudo systemctl start settingsservice
----

[#ext-api]
== Установка Сервиса внешнего API {of-mc}

. Установите сервис внешнего API:
+
[source,bash]
----
sudo apt-get install externalapi
----
+
. Замените или отредактируйте файл настроек:
+
[source,bash]
----
sudo cp ~/tech_days/ExternalAPI/appsettings.json /usr/lib/docsvision/ExternalAPI/appsettings.json
----
+
. Запустите сервис внешнего API {of-mc}:
+
[source,bash]
----
sudo systemctl start externalapi
----

include::upgrade:551-552:post-update.adoc[tags=console]

. Следующей командой установите {mc}:
+
[source,bash]
----
sudo apt-get install managementconsole
----
+
. Замените или отредактируйте файл настроек модуля:
+
[source,bash]
----
sudo cp ~/tech_days/ManagementConsole/appsettings.json /usr/lib/docsvision/ManagementConsole/appsettings.json
----
+
. Запустите службу:
+
[source,bash]
----
sudo systemctl start managementconsole
----
+
. Теперь вы можете открыть Консоль управления из браузера по адресу `\http://console.domain.com:5100`
+
NOTE: При авторизации укажите имя в формате `user@domain.com`, вариант `domain\user` не работает.

[#worker]
== Установка Службы {ws}

. Установите модуль Служба {ws} следующей командой:
+
[source,bash]
----
sudo apt-get install workerservice
----
+
. Замените или отредактируйте конфигурационный файл:
+
[source,bash]
----
sudo cp ~/tech_days/WorkerService/Configuration.json /usr/lib/docsvision/WorkerService/Configuration.json
----
+
. Запустите службу модуля:
+
[source,bash]
----
sudo systemctl start workerservice
----

[#purge]
== Удаление ненужных пакетов

. Удалите ненужные системе пакеты (зависимости, которые принесли за собой другие пакеты при установке) командой:
+
[source,bash]
----
sudo apt-get autoremove
----

Ознакомьтесь со списком полезных команд в пункте "xref:post-config-server.adoc[]".
