= Удаление системы

== Удаление на Linux

. Удалите пакеты установленных модулей системы, выполнив последовательно команды:
+
[lowerroman]
.. Удаление {wc}а:
+
[tabs]
====
Astra Linux::
+
 $ sudo apt-get purge docsvision-webclient

РЕД ОС::
+
 $ sudo dnf remove package docsvision-webclient
====
+
.. Удаление Сервиса настроек:
+
[tabs]
====
Astra Linux::
+
 $ sudo apt-get purge docsvision-settingsservice

РЕД ОС::
+
 $ sudo dnf remove package docsvision-settingsservice
====
+
.. Удаление Сервиса внешнего API {of-mc}:
+
[tabs]
====
Astra Linux::
+
 $ sudo apt-get purge docsvision-externalapi

РЕД ОС::
+
 $ sudo dnf remove package docsvision-externalapi
====
+
.. Удаление Службы {ws}:
+
[tabs]
====
Astra Linux::
+
 $ sudo apt-get docsvision-workerservice

РЕД ОС::
+
 $ sudo dnf remove docsvision-workerservice
====
+
.. Удаление Платформы:
+
[tabs]
====
Astra Linux::
+
 $ sudo apt-get purge docsvision-platform

РЕД ОС::
+
 $ sudo dnf remove package docsvision-platform
====
+
.. Удаление ненужных пакетов:
+
[tabs]
====
Astra Linux::
+
 $ sudo apt-get autoremove

РЕД ОС::
+
 $ sudo dnf autoremove
====

== Удаление на Windows

Порядок удаления системы {dv} не регламентирован. Порядок удаления для модулей следует уточнять в документации по администрированию соответствующего модуля. Как правило, серверная часть должна быть удалена в первую очередь.

Только после удаления других модулей системы {dv} следует приступать к удалению модуля _{pl}_ в следующем порядке:

. _{pl}_. Сервер.
. _{pl}_. Клиент.

Компоненты модуля _{pl}_ следует удалять только после удаления других модулей {dv}. Если не все другие модули были удалены предварительно, система не позволит продолжить удаление.
