= Удаление системы

== Удаление на Linux

. Удалите пакеты установленных модулей системы, выполнив последовательно команды:
+
[lowerroman]
.. Удаление {wc}а:
+
 $ sudo apt-get purge webclient
+
.. Удаление Сервиса настроек:
+
 $ sudo apt-get purge settingsservice
+
.. Удаление Сервиса внешнего API {of-mc}:
+
 $ sudo apt-get purge externalapi
+
.. Удаление Службы {ws}:
+
 $ sudo apt-get purge workerservice
+
.. Удаление Платформы:
+
 $ sudo apt-get purge platform
+
.. Удаление ненужных пакетов:
+
 $ sudo apt-get autoremove

== Удаление на Windows

Порядок удаления системы {dv} не регламентирован. Порядок удаления для модулей следует уточнять в документации по администрированию соответствующего модуля. Как правило, серверная часть должна быть удалена в первую очередь.

Только после удаления других модулей системы {dv} следует приступать к удалению модуля _{pl}_ в следующем порядке:

. _{pl}_. Сервер.
. _{pl}_. Клиент.

Компоненты модуля _{pl}_ следует удалять только после удаления других модулей {dv}. Если не все другие модули были удалены предварительно, система не позволит продолжить удаление.
