= Распространение клиентских компонентов модулей через групповую политику

Клиентские части модулей могут быть установлены с использованием групповых политик.

Чтобы распространить клиентские части с использованием групповых политик, в первую очередь необходимо создать каталог на сервере, из которого будут установлены все клиентские дистрибутивы и поместить в него все клиентские `.msi`.

NOTE: Следующие шаги выполняются на машине с клиентскими дистрибутивами.

[#createCommonDirectory]
== Создайте общий каталог

. Создайте на сервере каталог и поместите в него все клиентские `.msi`
. В свойствах каталога, на вкладке _Доступ_ задайте необходимые настройки общего доступа.
+
Чтобы установка клиентских дистрибутивов прошла успешно, пользователи или группы пользователей должны обладать правами на чтение и выполнение каталога (`*Read & execute*`).
+
Если клиентская часть модулей на целевых компьютерах установлена с областью установки _для текущего пользователя_, *самостоятельно удалите ВСЕ клиентские компоненты старой версии* до установки новой, в ином случае в ОС будут параллельно существовать старая и новая версии.
+
. Скопируйте *сетевой* путь к каталогу с клиентскими дистрибутивами.

[#createScript]
== Создайте скрипт для установки клиентских дистрибутивов

[start=4]
. Откройте текстовый редактор (например, Блокнот), чтобы создать новый файл.
. Скопируйте и вставьте следующий скрипт в окно редактора:
+
[source,shell]
----
msiexec /i "Docsvision Platform client.msi" ALLUSERS=1 /quiet <.> <.>
msiexec /i "Docsvision Worker service client.msi" ALLUSERS=1 /quiet
msiexec /i "Docsvision WindowsClient.msi" ALLUSERS=1 /quiet DVURL="http://company.com/docsvision" <.>
msiexec /i "Docsvision ApprovalDesigner client.msi" ALLUSERS=1 /quiet
msiexec /i "Docsvision BackOffice client.msi" ALLUSERS=1 /quiet
msiexec /i "Docsvision DocumentManagement client.msi" ALLUSERS=1 /quiet
msiexec /i "Docsvision TakeOffice client.msi" ALLUSERS=1 /quiet
msiexec /i "Docsvision Workflow client.msi" ALLUSERS=1 /quiet
<.>
----
<.> `Docsvision Platform client.msi` -- полный сетевой путь, скопированный на шаге 3.
<.> Флаг `ALLUSERS=1` означает, что установка будет производиться для всех пользователей.
+
+
WARNING: Не используйте групповые политики, если требуется установить дистрибутивы только для текущего пользователя.
+
<.> `DVURL="http://company.com/docsvision"` -- адрес подключения к серверу _Docsvision_.
<.> Список может быть расширен дополнительными модулями и утилитами.
+
WARNING: Строка с командой установки клиентской части модуля _{to}_ всегда должна располагаться ниже строки с установкой клиентской части модуля {wincl}.
+
. Сохраните файл с расширением консоли (`.bat`) в каталог на сервере, созданный <<createCommonDirectory,ранее>>.
+
WARNING: Если вы хотите сохранить файл в другой каталог, измените путь к инсталляторам.

[#createGPO]
== Создайте групповую политику

[start=7]
. На сервере, в диспетчере серверов откройте menu:Средства[Локальные групповые политики].
. Раскройте лес Active Directory, домен и выберите контейнер _Объекты групповой политики_.
. Правой кнопкой мыши нажмите на контейнер, выберите _Новая групповая политика_.
. В диалоговом окне введите новое имя для создаваемой групповой политики.
. Правой кнопкой мыши кликните на созданную групповую политику, в контекстном меню выберите пункт _Редактировать_.

== Создайте сценарий автозагрузки

[start=12]
. В редакторе групповых политик перейдите в раздел menu:Конфигурация компьютера[Политики > Сценарии (запуск/завершение)].
. Двойным нажатием выберите пункт _Автозагрузка_ и нажмите кнопку *Добавить*.
. Нажмите кнопку *Обзор*, чтобы открыть окно проводника и выберите <<createScript,созданный ранее>> файл скрипта.
//+
//. В поле _Параметры сценария_ укажите следующую строку, чтобы запустить установку от имени администратора:
//+
//[source,shell]
//----
//Runas /profile /user:domainname\administrator cwClientDeploy.bat
//----
+
NOTE: Скрипты автозагрузки выполняются от имени учётной записи _LocalSystem_. Для скриптов, выполняемых от имени _LocalSystem_ действуют полные права, такие же как для учётной записи _LocalSystem_.
+
. Завершите конфигурацию, нажав кнопку *ОК* в окне _Свойства: Автозагрузка_ и закройте окно.

== Свяжите групповую политику

[start=16]
. В окне консоли _Управления групповой политикой_ нажмите правой кнопкой на желаемый элемент: домен, сайт или лес и выберите пункт _Связать существующий объект групповой политики_ из контекстного меню.
. В диалоге выбора Объекта групповой политики выберите групповую политику <<createGPO,созданную ранее>>.
//. Again navigate to the newly created policy and click on Settings tab. Verify that the Script execute policy is showing active underneath the computer setting tree.
//. Go to Scope tab and enforce this policy to its group. Add and apply the same settings to any particular users or groups, if you wish to.
. Сценарий автозагрузки будет запущен на компьютерах, к которым применена групповая политика.
+
NOTE: Распространение групповых политик занимает время. Если вы хотите распространить групповые политики сразу, используйте команду `gpupdate /force`.
+
. Чтобы избежать повторного запуска установки, удалите компьютер из групповой политики после первого перезапуска. Отключите групповую политику, когда все компьютеры были перезапущены.

//reference: https://www.currentware.com/support/how-do-i-deploy-the-currentware-client-using-active-directory-batch-file/