= Действия после установки серверной части модулей

[#disable-cache]
== Отключите клиентское кэширование

Рекомендуется отключить кэширование карточек и файлов на компьютере с сервером {dv}, для избежания переполнения клиентского кэша из-за работы СУБП, следствием чего может стать замедление обработки БП.

. Откройте _Редактор реестра_.
. Перейдите к ветке `{hklm-dv}\Platform\ObjectManager`.
+
Если раздел ObjectManager отсутствует, создайте его самостоятельно.
+
. Создайте или измените параметр `CacheMode`:
+
* Тип: `DWORD`
* Значение: `4`
+
. Повторите шаги 2-3 для ветки `{hklm}\SOFTWARE\Wow6432Node\Docsvision\Platform\ObjectManager`.
. Перезапустите службу *{wfs-new}*.

[#account-rights]
== Предоставьте права учетным записям сервисов {dv}

.Серверная часть {dv} устанавливает в ОС Windows собственные сервисы:
Сервер {dv}::
Включает службу *{sss-new}* и веб-приложение сервера {dv}, размещенное в IIS. Сервер {dv} обеспечивает возможность подключения клиентских приложений.

Сервис полнотекстового индексирования::
*{fts-new}*. Сервис полнотекстового индексирования обеспечивает индексацию данных в БД {dv}.

Сервис отложенных операций с файлами::
*{fss-new}*. Сервис отложенных операций с файлами удаляет файлы из хранилища бинарных данных файлов, а также переносит бинарные данные файлов из одного хранилища в другое.

Сервис управления бизнес-процессами (СУБП)::
*{wfs-new}*. СУБП обрабатывает бизнес-процессы {dv}.

[NOTE]
====
Администратор должен самостоятельно настроить права учетных записей указанных выше служб. Учётные записи можно объединить в группу для удобства назначения прав.

Требования учетных записей сервисов {dv} приведены в документации модуля {pl}, раздел "xref:dev@platform::requirements-server-account.adoc[]".

Рекомендуется xref:dev@platform:console:manage-licenses.adoc#personalLicense[назначить] учетным записям сервиса полнотекстового индексирования и СУБП персональную лицензию.
====

Служба {ws}::
Служба *{wss-new}* предназначена для выполнения задач, поступивших от других модулей {dv} в фоновом режиме.

include::upgrade:551-552:post-update.adoc[tags=console]
